"""
Email Formatter & Sender — renders OpenRouter-generated markdown reports into HTML email.

The markdown content passed here is the exact same markdown that is displayed on the
localhost web UI (generated by OpenRouter + ClickUp MCP tools). This ensures the email
report is identical to what you see on the local page.
"""

import html
import re
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime, timezone, timedelta
from typing import List

IST = timezone(timedelta(hours=5, minutes=30))


# ---------------------------------------------------------------------------
# Markdown → HTML renderer (matches the style of the api_server.py web UI)
# ---------------------------------------------------------------------------


def _md_inline(text: str) -> str:
    """Convert inline markdown (bold, italic, inline-code) to HTML."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"__(.+?)__", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(
        r"`(.+?)`",
        r'<code style="background:#21262d;padding:2px 6px;border-radius:4px;">\1</code>',
        text,
    )
    return text


def _render_markdown(markdown: str) -> str:
    """Convert a markdown string to styled HTML matching the localhost page aesthetic."""
    lines = (markdown or "").splitlines()
    out: List[str] = []
    i = 0

    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()

        # Blank line
        if not stripped:
            i += 1
            continue

        # Horizontal rule
        if re.match(r"^[-*_]{3,}\s*$", stripped):
            out.append(
                '<hr style="border:0;border-top:1px solid #30363d;margin:16px 0;">'
            )
            i += 1
            continue

        # ATX headings
        m = re.match(r"^(#{1,6})\s+(.*)", stripped)
        if m:
            level = len(m.group(1))
            content = _md_inline(html.escape(m.group(2).strip()))
            col = {1: "#58a6ff", 2: "#79c0ff", 3: "#d2a8ff"}.get(level, "#c9d1d9")
            sz = {1: "20px", 2: "17px", 3: "15px"}.get(level, "13px")
            mt = {1: "22px", 2: "18px", 3: "14px"}.get(level, "10px")
            out.append(
                f'<h{level} style="color:{col};font-size:{sz};margin:{mt} 0 8px;'
                f'border-bottom:1px solid #30363d;padding-bottom:6px;">{content}</h{level}>'
            )
            i += 1
            continue

        # Table (header row followed by divider row)
        if "|" in stripped and i + 1 < len(lines):
            next_stripped = lines[i + 1].strip()
            if re.match(r"^[\s|:\-]+$", next_stripped) and "|" in next_stripped:
                headers = [c.strip() for c in stripped.strip("|").split("|")]
                i += 2  # skip header + divider
                rows: List[List[str]] = []
                while i < len(lines) and "|" in lines[i]:
                    cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                    rows.append(cells)
                    i += 1

                t = (
                    '<table style="border-collapse:collapse;width:100%;margin:10px 0 20px 0;'
                    'background:#161b22;border-radius:6px;overflow:hidden;">'
                    "<thead><tr>"
                )
                for h in headers:
                    t += (
                        '<th style="background:#21262d;color:#58a6ff;padding:10px 14px;'
                        'text-align:left;font-size:13px;border-bottom:1px solid #30363d;">'
                        f"{html.escape(h)}</th>"
                    )
                t += "</tr></thead><tbody>"
                for row in rows:
                    t += "<tr>"
                    for cell in row:
                        t += (
                            '<td style="padding:8px 14px;border-bottom:1px solid #21262d;'
                            f'font-size:13px;color:#c9d1d9;">{_md_inline(html.escape(cell))}</td>'
                        )
                    t += "</tr>"
                t += "</tbody></table>"
                out.append(t)
                continue

        # Unordered list
        if re.match(r"^[-*+]\s+", stripped):
            items: List[str] = []
            while i < len(lines) and re.match(r"^[-*+]\s+", lines[i].strip()):
                item_text = re.sub(r"^[-*+]\s+", "", lines[i].strip())
                items.append(
                    f'<li style="margin:4px 0;color:#c9d1d9;">'
                    f"{_md_inline(html.escape(item_text))}</li>"
                )
                i += 1
            out.append(
                '<ul style="margin:8px 0 12px 20px;padding:0;">'
                + "".join(items)
                + "</ul>"
            )
            continue

        # Ordered list
        if re.match(r"^\d+\.\s+", stripped):
            items = []
            while i < len(lines) and re.match(r"^\d+\.\s+", lines[i].strip()):
                item_text = re.sub(r"^\d+\.\s+", "", lines[i].strip())
                items.append(
                    f'<li style="margin:4px 0;color:#c9d1d9;">'
                    f"{_md_inline(html.escape(item_text))}</li>"
                )
                i += 1
            out.append(
                '<ol style="margin:8px 0 12px 20px;padding:0;">'
                + "".join(items)
                + "</ol>"
            )
            continue

        # Paragraph
        out.append(
            f'<p style="margin:6px 0;color:#c9d1d9;font-size:13px;">'
            f"{_md_inline(html.escape(stripped))}</p>"
        )
        i += 1

    return "\n".join(out)


# ---------------------------------------------------------------------------
# Email content builders
# ---------------------------------------------------------------------------


def _build_html_email(reports_markdown: List[dict], schedule_label: str) -> str:
    """Build full HTML email body from a list of OpenRouter markdown reports."""
    now_ist = datetime.now(IST).strftime("%Y-%m-%d %H:%M IST")

    body = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  .report-header {{ border-bottom: 2px solid #30363d; padding-bottom: 14px; margin-bottom: 20px; }}
  .report-title {{ color: #58a6ff; font-size: 22px; margin: 0 0 6px; }}
  .meta {{ color: #8b949e; font-size: 13px; }}
  .space-block {{ border: 1px solid #30363d; border-radius: 8px; padding: 18px 22px; margin: 20px 0; background: #161b22; }}
  .error-box {{ color: #f85149; background: #1c0c0c; border: 1px solid #3d1414; padding: 12px; border-radius: 6px; font-size: 13px; }}
  .no-data {{ color: #8b949e; font-style: italic; font-size: 13px; }}
  .footer {{ color: #484f58; font-size: 11px; margin-top: 30px; border-top: 1px solid #21262d; padding-top: 12px; }}
</style>
</head>
<body>
<div class="container">
  <div class="report-header">
    <h1 class="report-title">📊 ClickUp Daily Report — {html.escape(schedule_label)}</h1>
    <p class="meta">Generated: {now_ist}&nbsp;&nbsp;|&nbsp;&nbsp;Reports via OpenRouter + ClickUp MCP (identical to localhost page)</p>
  </div>
"""

    for entry in reports_markdown:
        space = entry.get("space", "Unknown")
        error = entry.get("error")
        markdown = (entry.get("markdown") or "").strip()

        body += '<div class="space-block">'

        if error:
            body += f'<h2 style="color:#f85149;font-size:17px;margin:0 0 12px;">🔴 {html.escape(space)}</h2>'
            body += f'<div class="error-box"><strong>Error:</strong> {html.escape(str(error))}</div>'
        elif not markdown:
            body += f'<h2 style="color:#79c0ff;font-size:17px;margin:0 0 12px;">📁 {html.escape(space)}</h2>'
            body += '<p class="no-data">No report data was returned for this space.</p>'
        else:
            # Render the exact markdown the OpenRouter model produced
            body += _render_markdown(markdown)

        body += "</div>\n"

    body += (
        '<div class="footer">'
        "Auto-generated by ClickUp Motia Reports &bull; Powered by OpenRouter + ClickUp MCP"
        "</div>"
    )
    body += "\n</div></body></html>"
    return body


def _build_combined_md(reports_markdown: List[dict], schedule_label: str) -> str:
    """Build a combined .md attachment from all space reports."""
    now_ist = datetime.now(IST).strftime("%Y-%m-%d %H:%M IST")
    parts = [
        f"# ClickUp Daily Report — {schedule_label}",
        "",
        f"Generated: {now_ist}",
        "",
        "---",
        "",
    ]

    for entry in reports_markdown:
        space = entry.get("space", "Unknown")
        error = entry.get("error")
        markdown = (entry.get("markdown") or "").strip()

        if error:
            parts += [f"## ❌ {space}", "", f"**Error:** {error}", "", "---", ""]
        elif not markdown:
            parts += [f"## {space}", "", "_No report data received._", "", "---", ""]
        else:
            parts += [markdown, "", "---", ""]

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Public send function
# ---------------------------------------------------------------------------


def send_report_email(
    reports_markdown: List[dict],
    schedule_label: str,
    smtp_host: str,
    smtp_port: int,
    smtp_email: str,
    smtp_password: str,
    to_email: str,
) -> dict:
    """
    Format and send the report email.

    Args:
        reports_markdown: List of {"space": str, "markdown": str|None, "error": str|None}.
                          The markdown strings are the raw OpenRouter outputs — same as
                          what the localhost web UI displays.
    """
    now_ist = datetime.now(IST)
    date_str = now_ist.strftime("%Y-%m-%d")

    html_body = _build_html_email(reports_markdown, schedule_label)
    md_content = _build_combined_md(reports_markdown, schedule_label)

    msg = MIMEMultipart("mixed")
    msg["From"] = smtp_email
    msg["To"] = to_email
    msg["Subject"] = f"📊 ClickUp Report — {schedule_label} — {date_str}"

    # HTML body part
    msg.attach(MIMEText(html_body, "html"))

    # .md attachment
    md_filename = (
        f"clickup_report_{schedule_label.lower().replace(' ', '_')}_{date_str}.md"
    )
    md_part = MIMEBase("application", "octet-stream")
    md_part.set_payload(md_content.encode("utf-8"))
    encoders.encode_base64(md_part)
    md_part.add_header("Content-Disposition", f'attachment; filename="{md_filename}"')
    msg.attach(md_part)

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.send_message(msg)
        return {
            "status": "sent",
            "to": to_email,
            "subject": msg["Subject"],
            "spaces_included": len(reports_markdown),
            "sent_at": now_ist.strftime("%Y-%m-%d %H:%M:%S IST"),
        }
    except Exception as exc:
        return {
            "status": "failed",
            "error": str(exc),
            "to": to_email,
        }


def _build_html_report(reports: List[dict], schedule_label: str) -> str:
    """Build a single HTML email body from all space reports."""

    now_ist = datetime.now(IST).strftime("%Y-%m-%d %H:%M IST")

    html = f"""
    <html>
    <head>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        h1 {{ color: #58a6ff; border-bottom: 2px solid #30363d; padding-bottom: 12px; font-size: 22px; }}
        h2 {{ color: #79c0ff; margin-top: 28px; font-size: 18px; }}
        h3 {{ color: #d2a8ff; font-size: 15px; margin-top: 18px; }}
        .meta {{ color: #8b949e; font-size: 13px; margin-bottom: 20px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 10px 0 20px 0; background: #161b22; border-radius: 6px; overflow: hidden; }}
        th {{ background: #21262d; color: #58a6ff; padding: 10px 14px; text-align: left; font-size: 13px; font-weight: 600; border-bottom: 1px solid #30363d; }}
        td {{ padding: 8px 14px; border-bottom: 1px solid #21262d; font-size: 13px; color: #c9d1d9; }}
        tr:hover td {{ background: #1c2128; }}
        .summary-box {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; margin: 12px 0; }}
        .summary-box span {{ display: inline-block; margin-right: 24px; }}
        .label {{ color: #8b949e; font-size: 12px; }}
        .value {{ color: #58a6ff; font-size: 16px; font-weight: bold; }}
        .error {{ color: #f85149; background: #1c0c0c; border: 1px solid #3d1414; padding: 10px; border-radius: 6px; }}
        .no-data {{ color: #8b949e; font-style: italic; }}
        .footer {{ color: #484f58; font-size: 11px; margin-top: 30px; border-top: 1px solid #21262d; padding-top: 12px; }}
    </style>
    </head>
    <body>
    <div class="container">
    <h1>📊 ClickUp Daily Report — {schedule_label}</h1>
    <p class="meta">Generated: {now_ist}</p>
    """

    for report in reports:
        space = report.get("space", "Unknown")

        if report.get("error"):
            html += f'<h2>🔴 {space}</h2><div class="error">{report["error"]}</div>'
            continue

        period = report.get("period", "")
        html += f"<h2>📁 {space}</h2>"
        html += f'<p class="meta">Period: {period} &nbsp;|&nbsp; <em>Time shown is cumulative time_spent on tasks updated in this period</em></p>'

        html += '<div class="summary-box">'
        html += f'<span><span class="label">Projects</span><br><span class="value">{report.get("active_projects", 0)}/{report.get("total_projects", 0)}</span></span>'
        html += f'<span><span class="label">Active Tasks</span><br><span class="value">{report.get("total_active_tasks", 0)}</span></span>'
        html += f'<span><span class="label">Tracked</span><br><span class="value">{report.get("total_tracked", "0h")}</span></span>'
        html += f'<span><span class="label">Estimated</span><br><span class="value">{report.get("total_estimated", "0h")}</span></span>'
        html += "</div>"

        projects = report.get("projects", [])
        if not projects:
            html += '<p class="no-data">No activity in this period.</p>'
            continue

        for proj in projects:
            html += f"<h3>📂 {proj['project']}</h3>"
            html += f'<p class="meta">{proj["active_tasks"]} active / {proj["total_tasks"]} total — Tracked: {proj["tracked"]} — Estimated: {proj["estimated"]}</p>'

            html += "<table><tr><th>Team Member</th><th>Tasks</th><th>Time Tracked</th></tr>"
            for m in proj.get("members", []):
                html += f"<tr><td>{m['name']}</td><td>{m['tasks_count']}</td><td>{m['tracked']}</td></tr>"
            html += "</table>"

    html += '<div class="footer">Auto-generated by ClickUp Motia Reports • Powered by Motia + iii</div>'
    html += "</div></body></html>"
    return html


def _build_markdown_report(reports: List[dict], schedule_label: str) -> str:
    """Build a markdown version of the report for .md attachment."""

    now_ist = datetime.now(IST).strftime("%Y-%m-%d %H:%M IST")
    md = f"# ClickUp Daily Report — {schedule_label}\n\n"
    md += f"Generated: {now_ist}\n\n---\n\n"

    for report in reports:
        space = report.get("space", "Unknown")

        if report.get("error"):
            md += f"## ❌ {space}\n\nError: {report['error']}\n\n---\n\n"
            continue

        period = report.get("period", "")
        md += f"## {space}\n\n"
        md += f"**Period:** {period}\n\n"
        md += f"| Metric | Value |\n|---|---|\n"
        md += f"| Projects (active/total) | {report.get('active_projects', 0)}/{report.get('total_projects', 0)} |\n"
        md += f"| Active Tasks | {report.get('total_active_tasks', 0)} |\n"
        md += f"| Total Tracked | {report.get('total_tracked', '0h')} |\n"
        md += f"| Total Estimated | {report.get('total_estimated', '0h')} |\n\n"

        projects = report.get("projects", [])
        if not projects:
            md += "_No activity in this period._\n\n---\n\n"
            continue

        for proj in projects:
            md += f"### {proj['project']}\n\n"
            md += f"{proj['active_tasks']} active / {proj['total_tasks']} total — "
            md += f"Tracked: {proj['tracked']} — Estimated: {proj['estimated']}\n\n"
            md += "| Team Member | Tasks | Time Tracked |\n|---|---|---|\n"
            for m in proj.get("members", []):
                md += f"| {m['name']} | {m['tasks_count']} | {m['tracked']} |\n"
            md += "\n"

        md += "---\n\n"

    return md


def send_report_email_legacy(
    reports: List[dict],
    schedule_label: str,
    smtp_host: str,
    smtp_port: int,
    smtp_email: str,
    smtp_password: str,
    to_email: str,
) -> dict:
    """
    Send HTML email with .md attachment.
    Returns status dict.
    """
    now_ist = datetime.now(IST)
    date_str = now_ist.strftime("%Y-%m-%d")

    # Build content
    html_body = _build_html_report(reports, schedule_label)
    md_content = _build_markdown_report(reports, schedule_label)

    # Compose email
    msg = MIMEMultipart("mixed")
    msg["From"] = smtp_email
    msg["To"] = to_email
    msg["Subject"] = f"📊 ClickUp Report — {schedule_label} — {date_str}"

    # HTML body
    html_part = MIMEText(html_body, "html")
    msg.attach(html_part)

    # .md attachment
    md_filename = (
        f"clickup_report_{schedule_label.lower().replace(' ', '_')}_{date_str}.md"
    )
    md_attachment = MIMEBase("application", "octet-stream")
    md_attachment.set_payload(md_content.encode("utf-8"))
    encoders.encode_base64(md_attachment)
    md_attachment.add_header(
        "Content-Disposition", f"attachment; filename={md_filename}"
    )
    msg.attach(md_attachment)

    # Send
    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.send_message(msg)
        return {
            "status": "sent",
            "to": to_email,
            "subject": msg["Subject"],
            "spaces_included": len(reports),
            "sent_at": now_ist.strftime("%Y-%m-%d %H:%M:%S IST"),
        }
    except Exception as e:
        return {
            "status": "failed",
            "error": str(e),
            "to": to_email,
        }

